
from SPARQLWrapper import SPARQLWrapper, JSON
from wikidata.client import Client
from wikidata.entity import EntityId

from itrack_spotipy.spotipy_app import models

import pprint
import sys

wikidata = models.WikiDataWrapper()

pp = pprint.PrettyPrinter(indent=4)

results = wikidata.search_track("JVG","55mdlQp6zN8zdyIYB9DDQj","247365","2tShA8neDBPFY0Bc06qEpx","Tarkenee","3G9gUGRgM4lB2ebVPUcMKI")
cleaned_results = wikidata.clean_results(results)
wrapped_results = wikidata.wrap_results(cleaned_results)
downloaded_results = wikidata.wikidata_download_results(wrapped_results)

pp.pprint(results)
print("\n\n\n")
pp.pprint(cleaned_results)
print("\n\n\n")
pp.pprint(wrapped_results)
print("\n\n\n")
pp.pprint(downloaded_results)
print("\n\n\n")

sys.stdout.flush()

results = wikidata.search_track("Nightwish","2NPduAUeLVsfIauhRwuft1","Once","13BVicwsbPLIaMvr6ivH6B","Wish I Had an Angel","6H8weEvfzCtffIIcwDOK6m")
cleaned_results = wikidata.clean_results(results)
wrapped_results = wikidata.wrap_results(cleaned_results)
downloaded_results = wikidata.wikidata_download_results(wrapped_results)

pp.pprint(results)
print("\n\n\n")
pp.pprint(cleaned_results)
print("\n\n\n")
pp.pprint(wrapped_results)
print("\n\n\n")
pp.pprint(downloaded_results)
print("\n\n\n")

sys.stdout.flush()

results = wikidata.search_track("Anthrax","3JysSUOyfVs1UQ0UaESheP","Persistence Of Time","1FZJXIaK7UEOWUXXChiUqv","Got The Time","62rSF7anVnDAmc9Vnmb7cH")
cleaned_results = wikidata.clean_results(results)
wrapped_results = wikidata.wrap_results(cleaned_results)
downloaded_results = wikidata.wikidata_download_results(wrapped_results)

pp.pprint(results)
print("\n\n\n")
pp.pprint(cleaned_results)
print("\n\n\n")
pp.pprint(wrapped_results)
print("\n\n\n")
pp.pprint(downloaded_results)
print("\n\n\n")

sys.stdout.flush()

results = wikidata.search_track("Sash!","5XTxV2ifoYkmNb13Gb6cKz","The Best Of","45XCMxMYVkiI9kh9P35MHz","Ecuador","5UuVC9noWHcsOX08ctdbDD")
cleaned_results = wikidata.clean_results(results)
wrapped_results = wikidata.wrap_results(cleaned_results)
downloaded_results = wikidata.wikidata_download_results(wrapped_results)

pp.pprint(results)
print("\n\n\n")
pp.pprint(cleaned_results)
print("\n\n\n")
pp.pprint(wrapped_results)
print("\n\n\n")
pp.pprint(downloaded_results)
print("\n\n\n")

sys.stdout.flush()

results = wikidata.search_track("Echosmith","1PbBg2aYjWLKRk84zJK15x","Talking Dreams (Deluxe Version)","23831oHY6eQmEG8skElDvFgKz2","Let's Love","4TPDqoA9k7jFtdigCgM2VT")
cleaned_results = wikidata.clean_results(results)
wrapped_results = wikidata.wrap_results(cleaned_results)
downloaded_results = wikidata.wikidata_download_results(wrapped_results)

pp.pprint(results)
print("\n\n\n")
pp.pprint(cleaned_results)
print("\n\n\n")
pp.pprint(wrapped_results)
print("\n\n\n")
pp.pprint(downloaded_results)
print("\n\n\n")

sys.stdout.flush()

results = wikidata.search_track("The All-American Rejects","3vAaWhdBR38Q02ohXqaNHT","When The World Comes Down","5doKZJ05r4UbAp9rmpDRDD","Real World","3RCCivI7aQPikuZjfSvyeY")
cleaned_results = wikidata.clean_results(results)
wrapped_results = wikidata.wrap_results(cleaned_results)
downloaded_results = wikidata.wikidata_download_results(wrapped_results)

pp.pprint(results)
print("\n\n\n")
pp.pprint(cleaned_results)
print("\n\n\n")
pp.pprint(wrapped_results)
print("\n\n\n")
pp.pprint(downloaded_results)
print("\n\n\n")

sys.stdout.flush()

results = wikidata.search_track("James Blunt","7KMqksf0UMdyA0UCf4R3ux","Some Kind Of Trouble (Deluxe Edition)","5b6T7m3DbNlWTwnaiuic2W","If Time Is All I Have - Acoustic","2t6Ep82FfXnuGLEHT1RnUj")
cleaned_results = wikidata.clean_results(results)
wrapped_results = wikidata.wrap_results(cleaned_results)
downloaded_results = wikidata.wikidata_download_results(wrapped_results)

pp.pprint(results)
print("\n\n\n")
pp.pprint(cleaned_results)
print("\n\n\n")
pp.pprint(wrapped_results)
print("\n\n\n")
pp.pprint(downloaded_results)
print("\n\n\n")

sys.stdout.flush()

results = wikidata.search_track("Mechina","056E4z3dLY3NlRs1w0YW5y","Empyrean","38V5f2Lk3hVExlJ2fxxCXX","Anathema","6uXTIXwpArDshw853fHiSO")
cleaned_results = wikidata.clean_results(results)
wrapped_results = wikidata.wrap_results(cleaned_results)
downloaded_results = wikidata.wikidata_download_results(wrapped_results)

pp.pprint(results)
print("\n\n\n")
pp.pprint(cleaned_results)
print("\n\n\n")
pp.pprint(wrapped_results)
print("\n\n\n")
pp.pprint(downloaded_results)
print("\n\n\n")

sys.stdout.flush()

artist_result = wikidata.query_artist("JVG","55mdlQp6zN8zdyIYB9DDQj")
cleaned_result = wikidata.clean_result(artist_result["bindings"][0],"artist","artistSpotifyId")
pp.pprint(artist_result)
print("\n\n\n")
pp.pprint(cleaned_result)
print("\n\n\n")
album_result = wikidata.query_album(cleaned_result["wikidata_id"],"247365","2tShA8neDBPFY0Bc06qEpx")
pp.pprint(album_result)
print("\n\n\n")
song_result = wikidata.query_song(cleaned_result["wikidata_id"],"Tarkenee","3G9gUGRgM4lB2ebVPUcMKI")
pp.pprint(song_result)
print("\n\n\n")
merged_result = wikidata.merge_results(artist_result,album_result,song_result)
pp.pprint(merged_result)
print("\n\n\n")

artist_result = wikidata.query_artist("Nightwish","2NPduAUeLVsfIauhRwuft1")
cleaned_result = wikidata.clean_result(artist_result["bindings"][0],"artist","artistSpotifyId")
pp.pprint(artist_result)
print("\n\n\n")
pp.pprint(cleaned_result)
print("\n\n\n")
album_result = wikidata.query_album(cleaned_result["wikidata_id"],"Once","13BVicwsbPLIaMvr6ivH6B")
pp.pprint(album_result)
print("\n\n\n")
song_result = wikidata.query_song(cleaned_result["wikidata_id"],"Wish I Had an Angel","6H8weEvfzCtffIIcwDOK6m")
pp.pprint(song_result)
print("\n\n\n")
merged_result = wikidata.merge_results(artist_result,album_result,song_result)
pp.pprint(merged_result)
print("\n\n\n")

artist_result = wikidata.query_artist("Anthrax","3JysSUOyfVs1UQ0UaESheP")
cleaned_result = wikidata.clean_result(artist_result["bindings"][0],"artist","artistSpotifyId")
pp.pprint(artist_result)
print("\n\n\n")
pp.pprint(cleaned_result)
print("\n\n\n")
album_result = wikidata.query_album(cleaned_result["wikidata_id"],"Persistence Of Time","1FZJXIaK7UEOWUXXChiUqv")
pp.pprint(album_result)
print("\n\n\n")
song_result = wikidata.query_song(cleaned_result["wikidata_id"],"Got The Time","62rSF7anVnDAmc9Vnmb7cH")
pp.pprint(song_result)
print("\n\n\n")
merged_result = wikidata.merge_results(artist_result,album_result,song_result)
pp.pprint(merged_result)
print("\n\n\n")

artist_result = wikidata.query_artist("Sash!","5XTxV2ifoYkmNb13Gb6cKz")
cleaned_result = wikidata.clean_result(artist_result["bindings"][0],"artist","artistSpotifyId")
pp.pprint(artist_result)
print("\n\n\n")
pp.pprint(cleaned_result)
print("\n\n\n")
album_result = wikidata.query_album(cleaned_result["wikidata_id"],"The Best Of","45XCMxMYVkiI9kh9P35MHz")
pp.pprint(album_result)
print("\n\n\n")
song_result = wikidata.query_song(cleaned_result["wikidata_id"],"Ecuador","5UuVC9noWHcsOX08ctdbDD")
pp.pprint(song_result)
print("\n\n\n")
merged_result = wikidata.merge_results(artist_result,album_result,song_result)
pp.pprint(merged_result)
print("\n\n\n")

artist_result = wikidata.query_artist("Echosmith","1PbBg2aYjWLKRk84zJK15x")
cleaned_result = wikidata.clean_result(artist_result["bindings"][0],"artist","artistSpotifyId")
pp.pprint(artist_result)
print("\n\n\n")
pp.pprint(cleaned_result)
print("\n\n\n")
album_result = wikidata.query_album(cleaned_result["wikidata_id"],"Talking Dreams (Deluxe Version)","23831oHY6eQmEG8skElDvFgKz2")
pp.pprint(album_result)
print("\n\n\n")
song_result = wikidata.query_song(cleaned_result["wikidata_id"],"Let's Love","4TPDqoA9k7jFtdigCgM2VT")
pp.pprint(song_result)
print("\n\n\n")
merged_result = wikidata.merge_results(artist_result,album_result,song_result)
pp.pprint(merged_result)
print("\n\n\n")
